Repository stolostron/metrics-collector, pull requests merged in 2021-03, with the labels that each got.

#1 prow update
  .travis.yml
  DCO
  Dockerfile.prow
  Makefile.prow
  _output/lib/zstd
Labels: approved, lgtm

#2 update dockerfile
  Dockerfile
  Dockerfile.prow
Labels: approved

#3 prow update
  .travis.yml
  Makefile.prow
  sonar-project.properties
Labels: approved

#4 for public repo, don't use ssh
  .travis.yml
Labels: approved, lgtm

#5 disable release_ff&publish in travis
  .travis.yml
Labels: approved, lgtm

#8 add contributing
  CONTRIBUTING.md
  RELEASE_FF_BRANCH
  RELEASE_MAIN_BRANCH
  go.mod
  go.sum
Labels: approved, lgtm

#9 non-op for ff/publish verify
  README.md
Labels: approved, lgtm

#10 enable e2e test with prow and remove travis.
  .travis.yml
  Makefile.prow
  cicd-scripts/run-e2e-tests.sh
Labels: approved, lgtm

#11 update readme
  README.md
  test/e2e/manifests/deployment_e2e.yaml
  test/e2e/test.sh
  test/integration/clean.sh
  test/integration/kind/kind-hub.config.yaml
  test/integration/manifests/client-serving-certs-ca-bundle.yaml
  test/integration/manifests/deployment.yaml
  test/integration/manifests/metrics-collector-cert.yaml
  test/integration/manifests/observatorium-api-configmap.yaml
  test/integration/manifests/observatorium-api-secret.yaml
  test/integration/manifests/observatorium-api-service.yaml
  test/integration/manifests/observatorium-api.yaml
  test/integration/manifests/observatorium-ca-cert.yaml
  test/integration/manifests/rolebinding.yaml
  test/integration/manifests/thanos-api.yaml
  test/integration/manifests/thanos-configmap.yaml
  test/integration/manifests/thanos-pvc.yaml
  test/integration/manifests/thanos-service.yaml
  test/integration/prereq.sh
  test/integration/setup.sh
Labels: approved, lgtm

#14 upgrade x/text to 0.3.5
  go.mod
  go.sum
Labels: approved, lgtm

#13 fix e2e test in 2.1
  temp/deployment.yaml
  temp/deployment_e2e.yaml
  temp/metrics-collector-cert.yaml
  temp/observatorium-api-configmap.yaml
  temp/observatorium-api-secret.yaml
  temp/observatorium-api-service.yaml
  temp/observatorium-api.yaml
  temp/observatorium-ca-cert.yaml
  temp/rolebinding.yaml
  temp/telemeter-client-serving-certs-ca-bundle.yaml
  temp/thanos-api.yaml
  temp/thanos-configmap.yaml
  temp/thanos-pvc.yaml
  temp/thanos-service.yaml
  test/e2e/setup.sh
Labels: lgtm
